name: ci

on:
  push:
    branches:
      - main
    # paths:
    #   - ".github/workflows/frontend.yml"
    #   - "frontend/**"

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          tags: ghcr.io/abendigo/github-repository:latest
          push: true
          # build-args: |
          #   "NPM_TOKEN=${{ secrets.GITHUB_TOKEN }}"
